### ISSUE TITLE
Does this still work with Ember 5.0?

### ISSUE THREAD

**Issue by roblopo** [alexlafroscia/ember-cli-stencil#59]
Not getting it to work with a set of components. Build is OK, but visiting my app throws:

Uncaught TypeError: (0 , _loader.applyPolyfills) is not a function
